// <auto-generated />
using System;
using Cats;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cats.Migrations
{
    [DbContext(typeof(CatsDbContext))]
    [Migration("20250602014746_AddBreedsImagePath")]
    partial class AddBreedsImagePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BreedsCoats", b =>
                {
                    b.Property<Guid>("BreedsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoatsId")
                        .HasColumnType("uuid");

                    b.HasKey("BreedsId", "CoatsId");

                    b.HasIndex("CoatsId");

                    b.ToTable("BreedsCoats");
                });

            modelBuilder.Entity("BreedsPersonalities", b =>
                {
                    b.Property<Guid>("BreedsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonalitiesId")
                        .HasColumnType("uuid");

                    b.HasKey("BreedsId", "PersonalitiesId");

                    b.HasIndex("PersonalitiesId");

                    b.ToTable("BreedsPersonalities");
                });

            modelBuilder.Entity("Cats.Entities.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinWeight")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Cats.Entities.Coat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Coats");
                });

            modelBuilder.Entity("Cats.Entities.Personality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Personalities");
                });

            modelBuilder.Entity("BreedsCoats", b =>
                {
                    b.HasOne("Cats.Entities.Breed", null)
                        .WithMany()
                        .HasForeignKey("BreedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cats.Entities.Coat", null)
                        .WithMany()
                        .HasForeignKey("CoatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BreedsPersonalities", b =>
                {
                    b.HasOne("Cats.Entities.Breed", null)
                        .WithMany()
                        .HasForeignKey("BreedsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cats.Entities.Personality", null)
                        .WithMany()
                        .HasForeignKey("PersonalitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
